export const CATEGORIES = [
  "Abarrotes",
  "Accesorios de Ferretería",
  "Accesorios de Limpieza",
  "Aceite",
  "Aceite de Maíz, Girasol y Canola",
  "Aceite de Oliva",
  "Aceite Vegetal",
  "Aceites Especiales",
  "Aceitunas en Conserva",
  "Acondicionador",
  "Aderezos, Sazonadores y Otros",
  "Afeitado",
  "Agua Mineral",
  "Agua Saborizada",
  "Agua Tónica",
  "Agua de Mesa",
  "Aguas",
  "Ají y Rocoto",
  "Ajo",
  "Ambientadores y Aromatizadores",
  "Apio, Espárrago y Otros Tallos",
  "Arena para gatos",
  "Arroz",
  "Arroz Extra",
  "Arroz Integral y Especiales",
  "Arroz Superior",
  "Artículos de Botiquín",
  "Arveja",
  "Arveja, Vainita, Haba y Otras Legumbres",
  "Avenas",
  "Azúcar Blanca",
  "Azúcar Rubia",
  "Azúcar en Polvo",
  "Azúcar y Endulzantes",
  "Baldes, Papeleras y Trapeadores",
  "Barras de Chocolate",
  "Barras Energéticas",
  "Bebidas",
  "Bebidas Funcionales",
  "Bebidas Refrescantes",
  "Bebidas Rehidratantes",
  "Bebé e Infantil",
  "Bocaditos",
  "Bocaditos Congelados",
  "Bolsas Conservadoras",
  "Bolsas para Basura",
  "Bombones",
  "Brócoli, Coliflor, Alcachofa y Col",
  "Cabanossi",
  "Café Instantáneo",
  "Café Molido",
  "Café e Infusiones",
  "Café en Granos",
  "Café en cápsulas",
  "Cajas Organizadoras",
  "Caldos en Cubitos",
  "Camotes, Chifles y Yucas",
  "Caramelos y Chupetes",
  "Carbón Y Mecheros Para Parrilla",
  "Carne Molida de Res",
  "Carnes, Arroces, Ensaladas y Purés",
  "Carnes, Aves y Pescados",
  "Cebolla, Ajo, Rocoto y Ají",
  "Cenas Navideñas",
  "Cepillos de Dientes",
  "Ceras y Limpiadores de Pisos",
  "Cerdo",
  "Cereales",
  "Cereales en Hojuelas",
  "Cervezas",
  "Cervezas Importadas",
  "Cervezas Nacionales",
  "Chocolatería",
  "Chocolates y Lentejas",
  "Choclo",
  "Chorizos",
  "Comida para gatos",
  "Comida para perros",
  "Comidas Instantáneas",
  "Comidas Listas",
  "Comidas Preparadas",
  "Complementos de Incontinencia",
  "Complementos de Licores",
  "Complementos y Suplementos",
  "Congelados",
  "Conservas",
  "Cortes Caseros de Res",
  "Cortes Parrilleros de Cerdo",
  "Cortes Parrilleros de Res",
  "Cortes de Pavita",
  "Cortes y Filetes de Pollo",
  "Cotillón para Fiesta",
  "Crema de Leche",
  "Cremas, Salsas y Condimentos a Granel",
  "Croquetas y comida seca para gatos",
  "Croquetas y comida seca para perros",
  "Cubiertos y complementos descartables",
  "Cuidado Bucal",
  "Cuidado Personal y Salud",
  "Cuidado de la Ropa",
  "Cuidado del Cabello",
  "Cuidado del Hogar",
  "Decohogar",
  "Desayunos",
  "Desinfectantes",
  "Desodorantes para Hombre",
  "Desodorantes para Mujer",
  "Detergentes Líquidos",
  "Detergentes en Polvo",
  "Elaborados de Cerdo",
  "Elaborados de Pollo",
  "Elaborados de Res",
  "Embutidos",
  "Ensaladas y Verduras Picadas",
  "Envases y empaques descartables",
  "Escobas y Recogedores",
  "Especias, Esencias y Decoración",
  "Espumantes",
  "Espumas y Gel de Afeitar",
  "Esponjas y Paños",
  "Ferretería",
  "Fideos Cortos",
  "Fideos Largos",
  "Fideos, Pastas y Salsas",
  "Fresa, Arándano, Aguaymanto y Otros Berries",
  "Frijol",
  "Frutas",
  "Frutas Congeladas",
  "Frutas en Conserva",
  "Frutas y Verduras",
  "Frutos Secos",
  "Galletas Dulces",
  "Galletas Saladas",
  "Galletas y Golosinas",
  "Galletas y snacks para perros",
  "Gallina",
  "Garbanzo",
  "Gaseosas",
  "Gaseosas Familiares",
  "Gaseosas Personales",
  "Gel Antibacterial",
  "Gelatina, Mazamorra y Pre mezclas",
  "Ginger Ale",
  "Gomitas y Gomas de Mascar",
  "Granolas y Salvado de Trigo",
  "Guantes Quirúrgicos",
  "Guantes y Escobillas",
  "Hamburguesas, Nuggets y Apanados",
  "Hamburguesas, Nuggets y Apanados Vegetarianos",
  "Hamburguesas, Nuggets y Apanados de Pollo",
  "Hamburguesas, Nuggets y Apanados de Res",
  "Harinas, Féculas y Polvo para Hornear",
  "Helados",
  "Helados y Postres",
  "Hielo",
  "Hierbas e Infusiones",
  "Higiene Personal",
  "Hongos, Setas y Germinados",
  "Hot Dogs",
  "Huevos",
  "Infusiones en Filtrantes",
  "Insecticidas y Raticidas",
  "Instantáneos y Cocoa",
  "Jabones Líquidos",
  "Jabones de Ropa",
  "Jabones en Barra",
  "Jamonada",
  "Jamonadas y Jamones Cocidos",
  "Jamón",
  "Jarabes y Siropes",
  "Jugos Naturales",
  "Jugos y Néctares",
  "Jugos y Otras Bebidas",
  "Kekes",
  "Ketchup",
  "Lácteos y Huevos",
  "Lavavajillas",
  "Leche",
  "Leche Chocolatada",
  "Leche Evaporada y Mezclas Lácteas",
  "Leche Fresca y UHT Larga Vida",
  "Leche condensada y Crema chantilly",
  "Leche de Soya y Otras Bebidas Vegetales",
  "Legumbres en Conserva",
  "Lejías",
  "Lenteja",
  "Librería y Oficina",
  "Licores",
  "Licores Preparados",
  "Limpiadores Multiusos",
  "Limpiadores de Muebles y Metales",
  "Limpiadores de Vidrios",
  "Limpiadores para Baño",
  "Limpieza",
  "Limpieza de Baño",
  "Limpieza de Cocina",
  "Limón",
  "Listos para servir",
  "Mantequilla",
  "Mantequilla de Maní y Almendras",
  "Mantequilla y Margarina",
  "Manzana, Pera y Membrillo",
  "Maní, Habas, Pistachos y Semillas",
  "Manjar Blanco y Dulce de Leche",
  "Maíz",
  "Maracuyá, Granadilla, Tuna y Tumbo",
  "Margarina",
  "Mariscos Congelados",
  "Mariscos Frescos",
  "Mascotas",
  "Mayonesa",
  "Mejoramiento del Hogar",
  "Melocotón, Durazno y Mango",
  "Menaje descartable",
  "Menaje, Utensilios y Moldes Descartables",
  "Menestras",
  "Menudencias de Pollo",
  "Menudencias de Res",
  "Mermeladas",
  "Mermeladas, Mieles y Dulces",
  "Mezclas para Apanar",
  "Miel y Algarrobina",
  "Modificadores de Leche",
  "Mostaza",
  "Máquinas de Afeitar y Repuestos",
  "Naranja, Mandarina y Otros Cítricos",
  "Organización del Hogar",
  "Organizadores de Cocina",
  "Otras Golosinas",
  "Otras Menestras",
  "Otros Accesorios de Limpieza",
  "Otros Cereales",
  "Otros Condimentos",
  "Otros Endulzantes",
  "Otros Espumantes",
  "Otros Fiambres",
  "Pallar",
  "Paltas",
  "Pan Envasado",
  "Pan Especial",
  "Pan Especial y Bollería Fina",
  "Pan Pita y Árabe",
  "Pan de Molde",
  "Pan de la Casa",
  "Panadería y Pastelería",
  "Panes Congelados",
  "Panes, Pastas, Bocaditos y Salsas",
  "Panetones",
  "Papa, Camote, Yuca y Otros Tubérculos",
  "Papaya y Piña",
  "Papel Film, Papel Aluminio, Papel Manteca y Otros",
  "Papel Higiénico",
  "Papel Toalla",
  "Papel para el Hogar",
  "Papelería",
  "Parrillas",
  "Pastas Congeladas",
  "Pastas Dentales",
  "Pastelería",
  "Pastillas y Destapa Cañerías",
  "Paté y comida húmeda para gatos",
  "Pavo, Pavita y Otras Aves",
  "Pañales para Bebé",
  "Pañales y Toallitas para Bebé",
  "Pescados Congelados",
  "Pescados Frescos",
  "Pescados en Conserva",
  "Pescados y Mariscos",
  "Piqueos Mixtos",
  "Pisco",
  "Plátano y Uva",
  "Pollo",
  "Pollo Entero",
  "Pollo Rostizado y Comidas Preparadas",
  "Pop Corn",
  "Postres",
  "Postres Congelados",
  "Protección Adulta",
  "Protección Femenina",
  "Protectores Diarios",
  "Queso Azul",
  "Queso Crema",
  "Queso Edam",
  "Queso Fresco",
  "Queso Fundido",
  "Queso Gouda",
  "Queso Mozzarella",
  "Queso Paria",
  "Queso Parmesano",
  "Quesos Blandos",
  "Quesos Duros",
  "Quesos Procesados",
  "Quesos Semiduros",
  "Quesos y Fiambres",
  "Quinua",
  "Quitamanchas",
  "Refrescos Instantáneos",
  "Regalos y Decoración para Fiestas",
  "Repostería",
  "Res",
  "Ron",
  "Sacagrasas",
  "Sal y Pimienta",
  "Salame",
  "Salames y Salchichones",
  "Salchichas",
  "Salchichas Frankfurter",
  "Salsas de Tomate",
  "Salsas especiales",
  "Salsas y Cremas",
  "Salsas, Cremas y Condimentos",
  "Salud",
  "Salud e higiene para gatos",
  "Sandwiches y enrollados",
  "Sandía y Melón",
  "Servilletas",
  "Shampoo",
  "Sillao",
  "Snacks y Piqueos",
  "Sopas",
  "Suavizantes",
  "Sémola y Fideos Especiales",
  "Tabletas de Chocolate",
  "Terraza y Aire Libre",
  "Toallas Higiénicas",
  "Toallitas Húmedas para Bebé",
  "Tocino",
  "Tomate, Pepino y Pimiento",
  "Tortillas",
  "Tortillas y Masas",
  "Tostadas, Crissinos y Galletas para Piqueo",
  "Velas para Cumpleaños",
  "Verduras",
  "Verduras Congeladas",
  "Verduras Orientales",
  "Verduras en Conserva",
  "Vinagre",
  "Vino Blanco",
  "Vino Rosé",
  "Vino Tinto",
  "Vinos",
  "Vinos, licores y cervezas",
  "Vitaminas y Nutrición",
  "Vodka",
  "Yogurt",
  "Yogurt Bebible",
  "Yogurt Especial y Funcional",
  "Yogurt Frutado",
  "Yogurt Griego",
  "Yogurt con Cereal",
  "Zanahoria, Beterraga, Rabanito y Otras Raíces",
  "Zapallo, Berenjena y Caigua",
  "Útiles Escolares y de Oficina",
];
